[mypy]
python_version = 3.12
ignore_missing_imports = true
warn_unused_ignores = true
check_untyped_defs = true
follow_imports = silent
files = corpus_store, url_utils.py

[mypy-corpus_store.*]
disallow_untyped_defs = false
